main: ru.eneontodo.russianroulette.RussianRoulettePlugin
version: 6.2
name: NutheRoulette
author: Eneontodo
api-version: "1.20"
description: Мини-игра «Русская рулетка» с системой лобби и локализацией.
commands:
  roulette:
    description: Основная команда плагина Russian Roulette.
    aliases: [rr]
    permission: russianroulette.use
    usage: "/roulette <join|leave|start|list|reload|lang>"
    permission-message: You don't have permission to use this command.

permissions:
  russianroulette.use:
    description: Allows players to use the /roulette command.
    default: true
  russianroulette.lang:
    description: Allows changing the plugin language.
    default: op
  russianroulette.reload:
    description: Allows reloading the plugin configuration and locales.
    default: op
